# Generated by Django 4.1.5 on 2023-01-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
    ]
